name: 'tax_rules'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'tax_rules'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  tax_rules:
    # Config indicated by + and applies to all files under models/staging/
    staging:
      +materialized: view
    # Config indicated by + and applies to all files under models/marts/
    marts:
      +materialized: table

# Sources configuration
sources:
  tax_rules:
    raw:
      database: province-development
      schema: raw
